name: DevOps
on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v3

      # 1. Instala o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # 2. Instala a CLI atual da Salesforce (@salesforce/cli)
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli

      # 3. Executa a validação
      - name: Validate Package Salesforce
        run: |
          mkdir -p config
          echo "force://${{ secrets.CLI_APP }}::${{ secrets.USER_TOKEN }}@${{ secrets.SF_URL }}" > config/auth.txt
          
          # Autenticação (funciona tanto com 'sf' quanto com alias 'sfdx')
          sf org login sfdx-url -f config/auth.txt -s -a MyOrg
          
          # Criação da Scratch Org e Deploy
          sf org create scratch -f config/project-scratch-def.json -a CIOrg -s -v MyOrg
          sf project deploy start -o CIOrg
          
          # Execução de Testes Apex
          sf apex run test -l RunLocalTests -o CIOrg -c -r human -w 2 --verbose
          
          # Deleção da Scratch Org
          sf org delete scratch -o CIOrg --no-prompt